// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOYrqZdpcws3BcnIwoJS7Xj8bH8_0PiJ8',
    appId: '1:466960844157:web:b0b1e3d2d5ecc39c177814',
    messagingSenderId: '466960844157',
    projectId: 'procuracao-app',
    authDomain: 'procuracao-app.firebaseapp.com',
    storageBucket: 'procuracao-app.appspot.com',
    measurementId: 'G-992R600WB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAmrBvI36YenJho7hW2WoHB0QF-4n3TUA',
    appId: '1:466960844157:android:c6b5717ab6a0e615177814',
    messagingSenderId: '466960844157',
    projectId: 'procuracao-app',
    storageBucket: 'procuracao-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpRSTIEgwXFPGWlHZLtcTBejp6Km0XDSw',
    appId: '1:466960844157:ios:718f58a1da051bb0177814',
    messagingSenderId: '466960844157',
    projectId: 'procuracao-app',
    storageBucket: 'procuracao-app.appspot.com',
    iosBundleId: 'com.example.procuracaoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpRSTIEgwXFPGWlHZLtcTBejp6Km0XDSw',
    appId: '1:466960844157:ios:718f58a1da051bb0177814',
    messagingSenderId: '466960844157',
    projectId: 'procuracao-app',
    storageBucket: 'procuracao-app.appspot.com',
    iosBundleId: 'com.example.procuracaoapp',
  );
}
